services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:4321
    ports:
      - "4321:80"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:4321/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: web-gis
      MYSQL_USER: admin
      MYSQL_PASSWORD: rahasia
      MYSQL_ROOT_PASSWORD: rahasiabanget
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  flask-app:
    build: flask
    restart: always
    ports: 
      - '4321:4321'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:4321/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:4321 app:app
    
volumes:
  mysql_data: